# Inherit from ProjectElixir
IS_PHONE := true
CUSTOM_BUILD_TYPE := OFFICIAL
Elixir_MAINTAINER := "Rahul Pal XDA"

TARGET_GAPPS_ARCH := arm64
TARGET_INCLUDE_STOCK_ACORE := false
TARGET_INCLUDE_LIVE_WALLPAPERS := false
TARGET_SUPPORTS_GOOGLE_RECORDER := false
TARGET_FACE_UNLOCK_SUPPORTED := true
